---
swagger: "2.0"
info:
  description: "A simple API to access the data and services of the project GeohistoricalData.\
    \ Find out more at [http://geohistoricaldata.org/api/docs](http://geohistoricaldata.org/api/docs)"
  version: "1.0.0"
  title: "GeohistoricalData API"
  termsOfService: ""
  contact:
    email: "contact@geohistoricaldata.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "geocoding"
  description: "Take one or several addresses to geocode and associate them with a\
    \ geohistorical object."
  externalDocs:
    description: "Find out more"
    url: "http://geohistoricaldata.org/api/docs/geocoding"
schemes:
- "http"
paths:
  /geocoding:
    post:
      tags:
      - "geocoding"
      summary: "Geocode an adress at a given date."
      description: "Some description."
      operationId: "geocode"
      consumes:
      - "application/xml"
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/GHObject"
      responses:
        200:
          description: "A set of geocoding candidates matching the queried address."
        400:
          description: "Invalid geocoding."
      x-swagger-router-controller: "Geocoding"
definitions:
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  GHObject:
    type: "object"
    required:
    - "address"
    - "date"
    properties:
      address:
        type: "string"
        example: "1 rue du Temple, Paris"
      date:
        type: "integer"
        example: 1850
      precision:
        type: "boolean"
        default: true
      maxresults:
        type: "integer"
    xml:
      name: "GHObject"
